In [1]:
# Installing required libraries

from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.ui import Select
import time

In [2]:
driver=webdriver.Chrome()  # setting up the driver

In [3]:
df=pd.read_csv('twitter_links.csv') # reading the file.
df

                               URL_LINKS
0             https://twitter.com/GTNUK1
1           https://twitter.com/whatsapp
2      https://twitter.com/aacb_CBPTrade
3         https://twitter.com/aacbdotcom
4   https://twitter.com/@AAWindowPRODUCT
5      https://www.twitter.com/aandb_kia
6          https://twitter.com/ABHomeInc
7            https://twitter.com/Abrepro
8                 http://www.twitter.com
9     https://twitter.com/ACChristofiLtd
10       https://twitter.com/aeclothing1
11               http://www.twitter.com/
12   https://twitter.com/AETechnologies1
13            http://www.twitter.com/wix
14    https://twitter.com/AGInsuranceLLC

In [4]:
bio=[]
following=[]
followers=[]
location=[]
site=[]
for i in range(len(df)):
    url=df.iloc[i][0] 
    driver.get(url) # getting the link 
    time.sleep(5) # to load the page completely
    
    # using try-catch block so that if data is unavailable code keep on executing.
    try:
        bio.append(driver.find_element(By.XPATH,"//div[@data-testid='UserDescription']//span").text) 
    except:
        bio.append('')
    try:
        following.append(driver.find_elements(By.XPATH,"//div[@class='css-1dbjc4n r-13awgt0 r-18u37iz r-1w6e6rj']//span[@class='css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0']")[0].text)
    except:
        following.append('')
    try:
        followers.append(driver.find_elements(By.XPATH,"//div[@class='css-1dbjc4n r-13awgt0 r-18u37iz r-1w6e6rj']//span[@class='css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0']")[2].text)
    except:
        followers.append('')
    try:
        location.append(driver.find_element(By.XPATH,"//span[@data-testid='UserLocation']").text)
    except:
        location.append('')
    try:
        site.append(driver.find_element(By.XPATH,"//div[@data-testid='UserProfileHeader_Items']//a").text)
    except:
        site.append('')

In [5]:
df1=pd.DataFrame(list(zip(bio,following,followers,location,site)),columns=['Bio','Following Count','Followers Count','Location','Website'])
df1

,Bio,Following Count,Followers Count,Location,Website
0,Providing Entertainment & Travel to Commercial...,465,128,"London, England",gtn.uk.com/index.php
1,#CrossingCultures,2,4.8M,California,bit.ly/3ZdxRY3
2,Customs Broker,125,29,"Florida, USA",
3,A & A Freight | Warehousing | Customs Brokerag...,"4,093",667,Worldwide,aacb.com
4,A commercial glass and glazing company serving...,91,76,"Malden, MA",aawindowproducts.com
5,"A&B Kia is a Kia dealer in Benwood, WV. Stay c...",347,301,"Benwood, West Virginia",aandbautosales.com
6,"Industry leader in wholesale home decor, furni...",184,368,"Rancho Cucamonga, CA",abhomeinc.com
7,From large format black & white prints to the ...,125,137,"Bentonville, AR",abrepro.com
8,,,,,
9,A & C CHRISTOFI LTD is a fast growing professi...,282,87,Cyprus,acccyp.com
10,Used Clothing Distributor,0,15,Carteret,aeclothing.net
11,,,,,
12,,1,38,"Boulder, CO USA",ae-technologies.com
13,"Create, manage and grow your business online w...","3,716",419.8K,We're everywhere!,wix.com
14,A & G Insurance prides itself on being your lo...,261,39,Connecticut,aginsuranceinc.com

In [6]:
df1.to_csv('Twitter_Bio.csv')